### ISSUE TITLE
Tutorial Overlay Screen

### ISSUE THREAD

**Issue by saysamarth** [Yash159357/BREVITY#58]
We want to introduce a tutorial overlay in our Flutter news app (Brevity) to guide new users through key features. This overlay should appear only once – right after the IntroScreen and when the user lands on the HomeScreen for the first time after signing up.

Tutorial Should Include:

👉 Swipe from Left to Right :- Highlight the gesture that takes the user to the Category Screen.

🤖 Tap the Chatbot Button :- Tell the user to click the bottom-right button to open Chatbot screen.

🔖 Tap News Heading to Bookmark :- Tell user that clicking headline adds the news to bookmarks.

Expected Behavior:

1) The tutorial should only run once per user, i.e., after the user signs up and lands on the HomeScreen for the first time.
2) You may use shared_preferences or any state management solution to persist the "seen tutorial" flag.
3) Smooth animations or overlay packages (e.g., tutorial_coach_mark or showcaseview) are preferred.

**Comment by debasmitaas** [comment]
I'm interested ,Can you please assign this issue to me

**Comment by saysamarth** [comment]
Hii @debasmitaas are you working on the issue ??

**Comment by debasmitaas** [comment]
@saysamarth  @suto6 Hello, i was working on this project, but due to some reason , when  i try to login , i get this error (attaching screenshots below) i do not know if this is because somebody is working on this or not , but it was working fine before, and i was debugging this tutorial_screen. But due to this error i cannot , please help me out as to what to do ?? (the sign up is working fine)

![Image](https://github.com/user-attachments/assets/d9ae4659-340d-4f20-b691-035bb2b024ee)
![Image](https://github.com/user-attachments/assets/2adc5572-938b-479b-a356-0c80148ce60b)

**Comment by saysamarth** [comment]
I think your issue must have been resolved now, 
If not try sign up and start working i will solve this issue permanently asap

**Comment by debasmitaas** [comment]
> I think your issue must have been resolved now, I will solve this issue permanently asap untill then you can try sign up and start working.

It did not resolve🥲, Also, after signing up , it still leads to login, so i cannot access the screens

**Comment by suto6** [comment]
@debasmitaas the issue is in backend (node js), it will take some days to resolve this

**Comment by saysamarth** [comment]
@garys-demons is mentor for the issue

**Comment by saysamarth** [comment]
Hi @debasmitaas, pull the code from main branch again, and then try running the app. I Hope it runs this time

**Comment by debasmitaas** [comment]
Hello , yes the login is working, But it doesn't redirect user to the main page.

**Comment by garys-demons** [comment]
@debasmitaas sorry but unfortunately we are going to have to remove as a contributor as it's been over a week since it was assigned to you and according to our contribution guidelines, issues can be unassigned if there is no activity till a week.

**Comment by Sanjana6261** [comment]
@saysamarth ,i would love to work on this issue please assign me

**Comment by garys-demons** [comment]
@Sanjana6261 assigning this to you
